---
logging:
  level: INFO
  loggers:
    org.example: DEBUG


greetingMessage: This is an Employee.

database:
  driverClass: org.postgresql.Driver
  user: postgres
  password: 1234
  url: jdbc:postgresql://localhost:5432/emsdropwizarddb

  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.hbm2ddl.auto: create
    hibernate.show_sql: true


swagger:
  resourcePackage: org.example.resources
  title: My API
  version: 1.0
  schemes:
    - http
  uriPrefix: /